"""Canonical enums shared across every component."""

from __future__ import annotations

from enum import StrEnum


class ClaimCategory(StrEnum):
    CONSULTATION = "CONSULTATION"
    DIAGNOSTIC = "DIAGNOSTIC"
    PHARMACY = "PHARMACY"
    DENTAL = "DENTAL"
    VISION = "VISION"
    ALTERNATIVE_MEDICINE = "ALTERNATIVE_MEDICINE"


class DocumentType(StrEnum):
    PRESCRIPTION = "PRESCRIPTION"
    HOSPITAL_BILL = "HOSPITAL_BILL"
    LAB_REPORT = "LAB_REPORT"
    PHARMACY_BILL = "PHARMACY_BILL"
    DIAGNOSTIC_REPORT = "DIAGNOSTIC_REPORT"
    DENTAL_REPORT = "DENTAL_REPORT"
    DISCHARGE_SUMMARY = "DISCHARGE_SUMMARY"
    UNKNOWN = "UNKNOWN"


class DocumentQuality(StrEnum):
    GOOD = "GOOD"
    POOR = "POOR"
    UNREADABLE = "UNREADABLE"


class Decision(StrEnum):
    APPROVED = "APPROVED"
    PARTIAL = "PARTIAL"
    REJECTED = "REJECTED"
    MANUAL_REVIEW = "MANUAL_REVIEW"


class ClaimStatus(StrEnum):
    DECIDED = "DECIDED"
    NEEDS_MEMBER_ACTION = "NEEDS_MEMBER_ACTION"
    PENDING_REVIEW = "PENDING_REVIEW"  # paused at a human-in-the-loop checkpoint


class RejectionReason(StrEnum):
    MEMBER_INVALID = "MEMBER_INVALID"
    POLICY_INACTIVE = "POLICY_INACTIVE"
    TREATMENT_DATE_INVALID = "TREATMENT_DATE_INVALID"
    SUBMISSION_DEADLINE_EXCEEDED = "SUBMISSION_DEADLINE_EXCEEDED"
    BELOW_MINIMUM_AMOUNT = "BELOW_MINIMUM_AMOUNT"
    CATEGORY_NOT_COVERED = "CATEGORY_NOT_COVERED"
    WAITING_PERIOD = "WAITING_PERIOD"
    EXCLUDED_CONDITION = "EXCLUDED_CONDITION"
    PRE_AUTH_MISSING = "PRE_AUTH_MISSING"
    PER_CLAIM_EXCEEDED = "PER_CLAIM_EXCEEDED"
    NOTHING_PAYABLE = "NOTHING_PAYABLE"


class DocumentProblemType(StrEnum):
    DOCUMENT_PRESENCE = "DOCUMENT_PRESENCE"
    DOCUMENT_READABILITY = "DOCUMENT_READABILITY"
    PATIENT_IDENTITY_MISMATCH = "PATIENT_IDENTITY_MISMATCH"
    CLAIM_DOCUMENT_MISMATCH = "CLAIM_DOCUMENT_MISMATCH"


class FraudSignalType(StrEnum):
    SAME_DAY_CLAIMS = "SAME_DAY_CLAIMS"
    MONTHLY_CLAIMS_EXCEEDED = "MONTHLY_CLAIMS_EXCEEDED"
    HIGH_VALUE_CLAIM = "HIGH_VALUE_CLAIM"
    HIGH_FRAUD_SCORE = "HIGH_FRAUD_SCORE"
    DOCUMENT_ALTERATION = "DOCUMENT_ALTERATION"


class LineItemStatus(StrEnum):
    COVERED = "COVERED"
    EXCLUDED = "EXCLUDED"
    REDUCED = "REDUCED"


class TraceStatus(StrEnum):
    PASS = "pass"
    FAIL = "fail"
    SKIP = "skip"
    INFO = "info"


class ExtractionMode(StrEnum):
    EVAL = "eval"
    LIVE = "live"
